import os

import archspec.cpu

archs = archspec.cpu.TARGETS

levels = {}

name_mapping = {
  "x86_64": 1,
  "x86_64_v2": 2,
  "x86_64_v3": 3,
  "x86_64_v4": 4,

  "ppc64le": 8,
  "power8le": 8,
  "power9le": 9,
  "power10le": 10,
}

for arch_name, arch in archs.items():
    if arch.family.name not in ("x86_64", "ppc64le"):
        continue
    levels[(arch_name, arch.family.name)] = max(
        1,
        name_mapping.get(arch_name, 0),
        *(name_mapping.get(parent.name, 0) for parent in (arch.ancestors or ()))
    )

levels = {arch: level for arch, level in sorted(
    levels.items(), key=lambda kv: kv[1])}

# Each row becomes one build of _{family}-microarch-level. Two styles:
#
# 1. Legacy: one build per microarchitecture name with an exact
#    `__archspec 1.* <name>` dependency. These keep conda and (micro)mamba
#    working, since they cannot match regex build strings in repodata. They
#    are down-prioritized via track_features (legacy="1" feeds
#    down_prioritize_variant in the recipe), so solvers that support the
#    regex (pixi/rattler) prefer the per-level builds; for the rest the
#    per-level builds are simply unsatisfiable candidates that are skipped
#    in favor of a legacy build.
# 2. Per-level: one build per (family, level) with a CEP 29 regex matching
#    every name of that level *or higher* in the family.
# Only the build matcher is stored in the variant; the recipe wraps it in the
# bracket-form spec __archspec[version='1.*', build='...']. Storing the full
# bracket spec would make the rendered .ci_support files end in `[...]`, which
# conda-build's line-selector parser (still used by conda-forge's
# validate_recipe_outputs) rejects as an invalid selector.
rows = []  # (build_tag, legacy, level, family, archspec_build)

for (arch_name, family), level in levels.items():
    rows.append((
        arch_name, 1, level, family,
        arch_name,
    ))

families = {}
for (arch_name, family), level in levels.items():
    families.setdefault(family, []).append((level, arch_name))

for family, named_levels in families.items():
    for level in sorted({level for level, _ in named_levels}):
        names = [name for lvl, name in sorted(named_levels) if lvl >= level]
        regex = "^(" + "|".join(names) + ")$"
        rows.append((
            f"level{level}", 0, level, family,
            regex,
        ))

out = [f"# This file is auto-generated by recipe/gen.py with archspec={archspec.__version__}"]
out.append("build_tag:")
for tag, _, _, _, _ in rows:
    out.append(f"- {tag}")
out.append("")
out.append("legacy:")
for _, legacy, _, _, _ in rows:
    out.append(f'- "{legacy}"')
out.append("")
out.append("level:")
for _, _, level, _, _ in rows:
    out.append(f'- "{level}"')
out.append("")
out.append("family:")
for _, _, _, family, _ in rows:
    out.append(f"- {family}")
out.append("")
out.append("archspec_build:")
for _, _, _, _, build in rows:
    out.append(f'- "{build}"')
out.append("""
zip_keys:
  - - build_tag
    - legacy
    - level
    - family
    - archspec_build""")

dest = os.path.join(os.path.dirname(__file__), "variants.yaml")
with open(dest, "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print(f"wrote {dest} ({len(rows)} rows)")
